### ISSUE TITLE
Intermittent: `Properties` update but not `Streams`

### ISSUE THREAD

**Issue by landlessness** [zettaios/zetta#7]
In the `Display Screen` details page served from `http://zetta-cloud-2.herokuapp.com/`, after I submit a `message` `change` request, the `message` field in the `Properties` section updates. But the `message` field in the `Streams` section does not.

It happens intermittently. To reproduce, go back and forth between the device list screen and the device details screen and submit a new `message`.

Screenshots attached. Notice that that value of the `message` values in `Properties` and `Streams` do not agree.

![img_1381](https://cloud.githubusercontent.com/assets/21422/13285247/96bb18ac-dac7-11e5-95e0-f8374faa7e9a.PNG)
![img_1382](https://cloud.githubusercontent.com/assets/21422/13285248/96bb83fa-dac7-11e5-8f3b-c365936dca83.PNG)

**Comment by benpackard** [comment]
Note to self: might be related to time. Leave a device screen open for a few minutes and attempt a change. Occasionally the property but not the stream gets updated. Can't be that the stream is no longer updating since that's what triggers the property cell to reload. Perhaps a bug in ZettaKit's `hashable` preventing `mostRecentStreamValues` from storing it correctly?

---

Actually, that's exactly what's happening. The action callback refreshes the device and the properties list. That's what reloads the properties cell. But the new value is never received by the stream signal, so therefore never stored to `mostRecentStramValues`.

**Comment by benpackard** [comment]
@mdobson Is there a time-out or similar that applies when subscribing to a `ZIKStream`'s signal? I've noticed that if I leave my device screen open for a few minutes and then send a transition (e.g. updating the display screen's message), no new `ZIKStreamEntry` is received.

**Comment by mdobson** [comment]
Web sockets have a built in timeout. The spec includes ways to send a ping
to keep the socket open. I'll look at adding support for it this week.

-Matt

_--_
_Matthew Dobson_ | _apigee https://apigee.com/_ | m: +1.734.634.5472 |
twitter @mdobs http://twitter.com/mdobs @apigee
https://twitter.com/apigee | _Apigee Community
http://community.apigee.com/_ for answers, ideas and support!

**Comment by benpackard** [comment]
I see, thanks.

**Comment by benpackard** [comment]
All streams now ping their socket periodically to stay alive.
